### ISSUE TITLE
Int field in schema and multi-verse texts

### ISSUE THREAD

**Issue by DCNemesis** [BibleNLP/bible-graph#1]
Let's say a translation has verse text associated with Genesis 1:1-5. Are we following the convention of putting all of that text in verse 1? Would String fields for chapter and verse make more sense, so that it could clearly indicate 1-5 (requiring logic to match on different references)? Especially as we deal with draft versions, how else would we distinguish between something with verses 2-5 still to be translated compared to one that has intentionally grouped 1-5 all in verse 1?

**Comment by dwhitena** [comment]
What I was thinking was that we would have a single versification as our "backbone" structure (maybe original versification based on the SIL NLP team's work on the internal/external corpus). Then we could load in any text in the original versification and have API calls to convert to other versifications. In the schema, this backbone is represented as:

```
type BookReference {
  id: ID!
  abbreviation: String! @id
  name: String! @search(by: [term, exact])
  number: Int! @search 
  chapterReferences: [ChapterReference!] @hasInverse(field: bookReference)
}

type ChapterReference {
  id: ID!
  number: Int! @search
  bookReference: BookReference!
  verseReferences: [VerseReference!] @hasInverse(field: chapterReference)
}

type VerseReference {
  id: ID!
  number: Int! @search
  chapterReference: ChapterReference!
}
```

(so the conversions of the Copenhagen Alliance would be implicit, not explicit)

Then for verse ranges, this would be handled by allowing Verse text nodes to link to multiple of the backbone verse references, as indicated here: 

```
type VerseText {
  id: ID!
  text: String! @search(by: [term])
  verseReference: [VerseReference!]
  bibleRevision: BibleRevision!
  assessmentDetails: [AssessmentDetail]
}
```
