### ISSUE TITLE
BCP-47 support in Schema

### ISSUE THREAD

**Issue by DCNemesis** [BibleNLP/bible-graph#16]
The bible-graph project may need support for BCP-47 to enable graceful input/output for versions, but does not necessarily need to have full BCP-47 throughout the internal graph structure. Posting this as an issue for future work and to document how I think it should proceed. According to the [Wikipedia page on BCP-47](https://en.wikipedia.org/wiki/IETF_language_tag) the syntax includes the following:

> - A single primary language subtag based on a two-letter language code from ISO 639-1 (2002) or a three-letter code from ISO 639-2 (1998), ISO 639-3 (2007) or ISO 639-5 (2008), or registered through the BCP 47 process and composed of five to eight letters;
> - Up to three optional extended language subtags composed of three letters each, separated by hyphens; (There is currently no extended language subtag registered in the Language Subtag Registry without an equivalent and preferred primary language subtag. This component of language tags is preserved for backwards compatibility and to allow for future parts of ISO 639.)
> - An optional script subtag, based on a four-letter script code from ISO 15924 (usually written in Title Case);
> - An optional region subtag based on a two-letter country code from ISO 3166-1 alpha-2 (usually written in upper case), or a three-digit code from UN M.49 for geographical regions;
> - Optional variant subtags, separated by hyphens, each composed of five to eight letters, or of four characters starting with a digit; (Variant subtags are registered with IANA and not associated with any external standard.)
> - Optional extension subtags, separated by hyphens, each composed of a single character, with the exception of the letter x, and a hyphen followed by one or more subtags of two to eight characters each, separated by hyphens;
> - An optional private-use subtag, composed of the letter x and a hyphen followed by subtags of one to eight characters each, separated by hyphens

- To support BCP-47 we would primary language subtag, we would need to link two-letter codes to three letter codes for input/output conversion. I [don't see any ](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry)examples of 5-8 letter codes registered through the BCP 47 process.
- optional extended language subtags ... a lot of these are for sign language and have a ISO equivalent now. It'd be mostly backwards compatibility support.
- We have script subtags
- region subtags ... these would link in to the BibleVersion, but are probably going to be limited to wider use languages which have variant translations (like the NIV UK). As these are excluded when redundant, they aren't going to be needed in many places. In fact ... if the rest of these are rare enough, we might be able to fold them up into a BCP-47 suffixes of some kind.
- extension subtags ... need examples
- private-use x tags for languages may help for emerging languages (e.g. Interslavic) that do not have ISO codes

Practically, the intent would be to store most things with ISO 639-3 and ISO 15924 in the main portion of the graph. For languages that do not have an ISO code, we could use a keyword like `"BCP47"` in place of the ISO code to key the API to search outside the main graph. Overall this would improve compatibility with things like the BibleNLP corpus that uses BCP-47, but I don't know that including these things in the graph instead of through the API (or other programs) is going to be a priority. The exception would be if someone has a Bible Version they want to add to the graph that requires some of the features above be implemented.

**Comment by dwhitena** [comment]
We should get Gary's input here. I don't think he is added to the BibleNLP group yet. @joelthe1 or @mmartin9684-sil can you add his Github user https://github.com/simonsg

**Comment by simonsg** [comment]
I was discussing something like this in another thread with Colin, but I'm not sure where that wasif it wasn't here. :-)  My basic point there was that BCP 47 is not another standard for language codes that needs to be supported.  Rather it is a set of rules that define how multipart tags encoding the language, dialect, and script of a document can be formed out of standardized codes.  It is the latter that are the real standards and we need to be putting those values into their respective fields, rather than storing this information as a denormalized composite.  If we need to ingest something that only has a BCP 47 language tag, then the ideal approach would be to submit the tag to an API (that should be out there already because it is just part of the global IT infrastructure) and get back its decomposition into standard codes for language, dialect, and script.  The latter are what we want for the properties in our graph database.

**Comment by dwhitena** [comment]
It seems like we have a grip on how to approach this issue, so I'm going to close this issue for now.
